### ISSUE TITLE
Lookup table creation

### ISSUE THREAD

**Issue by cmtippett** [nestauk/health-innovation-scanner#25]
Create lookup tables for geography (e.g. countries, US states) and types of null values

**Comment by mindrones** [comment]
We will need to discuss about having an endpoint to fetch the lookup tables for geographic entities (countries, states), and potentially other things like regions, continents, categories and ordinal values in general, to avoid repetitions in the query response.

**Comment by jaklinger** [comment]
These are available here:

https://console.aws.amazon.com/s3/buckets/nesta-open-data/rwjf-viz/?region=eu-west-2&tab=overview

Note: these are simply fetched from datahub.io

We're unlikely to provide a more robust solution until a later date when we work on geographic data infrastructure.

**Comment by mindrones** [comment]
At the moment these require authorization so they can't be used in the scanner as they are, we need to setup some form of static hosting ([1], [2]).

[1] https://docs.aws.amazon.com/AmazonS3/latest/dev/HowDoIWebsiteConfiguration.html
[2] https://miketabor.com/host-static-website-using-aws-s3/

**Comment by mindrones** [comment]
Ah the internal json files are publicly accessible, these are:
- https://nesta-open-data.s3.eu-west-2.amazonaws.com/rwjf-viz/continent_codes_names.json
- https://nesta-open-data.s3.eu-west-2.amazonaws.com/rwjf-viz/country_codes_names.json
- https://nesta-open-data.s3.eu-west-2.amazonaws.com/rwjf-viz/us_canada_states.json

**Comment by mindrones** [comment]
Unified the 3 json files into a single map and uploaded here: https://nesta-open-data.s3.eu-west-2.amazonaws.com/rwjf-viz/iso_a2_to_name_by_type.json

**Comment by mindrones** [comment]
Closing, thanks!
